#!/bin/bash
# List files in the current directory
echo "Files in the current directory:"
ls -l
# Move to the parent directory
cd ..
# List files in the parent directory
echo "Files in the parent directory:"
ls -l
# Move to the /boot directory
cd /boot
# List files in the /boot directory
echo "Files in the /boot directory:"
ls -l
