#!/bin/bash
current_dir=$(pwd)
parent_dir=$(dirname "$current_dir")
for file in *.html; do
    if [ -e "$parent_dir/$file" ]; then
    if [ "$current_dir/$file" -nt "$parent_dir/$file" ]; then
            cp "$file" "$parent_dir"
   echo "Copied '$file' to '$parent_dir'"
  fi
   else
 cp "$file" "$parent_dir"
  echo "Copied '$file' to '$parent_dir'"
fi
done
